### ISSUE TITLE
Edn stable depends on unstable peg

### ISSUE THREAD

**Issue by Malabarba** [expez/edn.el#4]
edn's stable release depends on the peg package, which is a wiki package and thus has no stable version on melpa. It would be nice to correct this. 

One way of doing this would be to add peg.el to edn's repo, and just drop the dependency altogether.
Another way would be for someone to add the package to github (possibly after trying to get in touch with [the author](http://www.emacswiki.org/emacs/peg.el)) and change its recipe accordingly.

**Comment by expez** [comment]
Does this mean `melpa-stable` won't work until this is fixed?

**Comment by Malabarba** [comment]
I mean a user who uses melpa-stable and not melpa won't be able to install `edn` until this is fixed. Which then extends to `clj-refactor` too.

**Comment by expez** [comment]
@ellerh any interest in putting your `peg.el` on github and creating a tag to make it available on `melpa-stable`?

**Comment by ellerh** [comment]
On Tue, Jul 07 2015, Lars Andersen wrote:

> @ellerh any interest in putting your peg.el on github and creating a tag to
> make it available on melpa-stable?

I've put up a copy on github.  What else must be done to make it
available on MELPA?

Helmut

**Comment by expez** [comment]
> I've put up a copy on github. 

Thanks!

> What else must be done to make it available on MELPA?

You have to create a tag so other packages can name a version to depend on.  I'll take care of the rest.

**Comment by ellerh** [comment]
On Wed, Jul 08 2015, Lars Andersen wrote:

> You have to create a tag so other packages can name a version to depend on.
> I'll take care of the rest.

What's a "tag"?

**Comment by Malabarba** [comment]
@ellerh A tag is a git tag, which you can create on the command line and then push. 
But you can also create them straight from Github's interface, like described [here](https://help.github.com/articles/creating-releases/), which might be simpler.

**Comment by Malabarba** [comment]
In order to do it from the command line, you should be able to just do the following:

```
git tag 1.0
git push origin --tags
```

Just make sure the tag name is a version number like `1.0` or `v1.0`.

**Comment by ellerh** [comment]
On Wed, Jul 08 2015, Artur Malabarba wrote:

> @ellerh A tag is a git tag, which you can create on the command line and then
> push.
> But you can also create them straight from Github's interface, like described
> here, which might be simpler.

Thanks.  I've created a tag named 0.6.

**Comment by expez** [comment]
Thanks a lot for your help, @ellerh!
